version: '3.8'

services:
  frontend:
    build:
      context: ./Front
    ports:
      - "3000:3000"
    container_name: frontend-container
    env_file:
      - /home/importent/.env
    networks:
      - k-wpu

  backend:
    build:
      context: ./Back
    ports:
      - "3001:8080"
    container_name: backend-container
    env_file:
      - /home/importent/.env
    networks:
      - k-wpu

networks:
  k-wpu:
    driver: bridge
