# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk

# Set the working directory
WORKDIR /app

# Copy the build artifact from the build context to the container
COPY build/libs/backend-app.jar /app/backend.jar

# Expose the port the app runs on
EXPOSE 8080

# Run the application
CMD ["java", "-jar", "backend.jar"]
