# JDK 설정
FROM openjdk:17-jdk

# 작업 폴더 설정
WORKDIR /app

# xargs 설치
RUN apt-get update && apt-get install -y findutils

# 빌드 파일 복사
COPY gradlew .
COPY gradlew.bat .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY src src

# 혹시모를 권한설정
RUN chmod +x gradlew

# 빌드
RUN ./gradlew build

# 결과 파일 복사
COPY build/libs/*.jar /app/backend.jar

# 포트 설정 (nginx에서 프록시할 것)
EXPOSE 8080

# Run 🚀
CMD ["java", "-jar", "backend.jar"]
