# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Set environment variable for the port
ENV PORT=80

# Build the React application
RUN npm run build

# Expose the port that the app runs on
EXPOSE 80

# Command to run the application
CMD ["npm", "start"]
